# Generated by Django 6.0.7 on 2026-07-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('caseworker', 'Case Worker'), ('viewer', 'Viewer')], db_index=True, default='viewer', help_text='Drives both UI rendering and DRF permission checks.', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('organization', models.CharField(blank=True, help_text='e.g. the NGO or government department the user represents.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The Django auth user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
