# Generated by Django 6.0.7 on 2026-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FosterFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(help_text="Synthetic identifier only — never a real family's name.", max_length=150)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(help_text='Maximum number of children this family can host at once.')),
                ('current_occupancy', models.PositiveSmallIntegerField(default=0)),
                ('experience_years', models.PositiveSmallIntegerField(help_text='Years this family has been an active foster placement.')),
                ('accepts_special_needs', models.BooleanField(default=False)),
                ('accepts_sibling_groups', models.BooleanField(default=False)),
                ('home_type', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive families are excluded from new placement recommendations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Foster families',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'is_active'], name='families_fo_state_15e11e_idx')],
            },
        ),
    ]
