# Generated by Django 6.0.7 on 2026-07-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosterfamily',
            name='background_clearance_status',
            field=models.CharField(choices=[('Cleared / Verified', 'Cleared / Verified'), ('Pending Review', 'Pending Review'), ('Incomplete', 'Incomplete')], default='Cleared / Verified', help_text='Status of criminal background check, fingerprinting & abuse registry checks', max_length=50),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='current_occupants',
            field=models.TextField(default='2 Permanent Adult Residents, 1 Biological Child (Age 10)', help_text='Names and ages of all permanent household residents for background clearance.'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='email_address',
            field=models.EmailField(default='family@fostercare.org', help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='identity_doc_number',
            field=models.CharField(default='Aadhaar/ID-9874-5612-3401', help_text='Aadhaar Card or official ID document number (Mandatory at least 1 person)', max_length=100),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='languages_spoken',
            field=models.CharField(blank=True, default='English, Spanish', help_text='Languages spoken in the home', max_length=200),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='license_expiration',
            field=models.DateField(blank=True, help_text='Expiration date of foster care license', null=True),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='license_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Suspended', 'Suspended'), ('Expired', 'Expired')], default='Active', help_text='Current foster licensing status', max_length=50),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='licensing_agency',
            field=models.CharField(default='State Department of Family & Protective Services', help_text='Licensing agency name', max_length=150),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='licensing_worker_name',
            field=models.CharField(default='Sarah Jenkins, LCSW', help_text='Assigned agency case manager overseeing this foster home', max_length=150),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='marital_status',
            field=models.CharField(blank=True, default='Married', help_text='Marital status & household composition details', max_length=100),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='phone_number',
            field=models.CharField(default='+1-555-0199', help_text='Primary phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='preferred_demographics',
            field=models.TextField(blank=True, default='Ages 0-12, Male or Female, Sibling groups up to 3', help_text='Preferred age range, gender, and sibling group preferences'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='primary_applicant_name',
            field=models.CharField(default='Primary Foster Parent', help_text='Full legal name(s) of the primary foster parent(s)', max_length=200),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='references_info',
            field=models.TextField(blank=True, default='1. Dr. Robert Miller (555-0142) - Family Physician\n2. Pastor James Vance (555-0188) - Community Reference', help_text='Personal and professional references submitted during home study'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='residential_address',
            field=models.TextField(default='123 Community Way, Suite 100', help_text='Full residential street address'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='special_trainings',
            field=models.TextField(blank=True, default='Trauma-Informed Care, CPR & Pediatric First Aid, Special Needs Certified', help_text='Special training, certifications, or medical competencies'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=2, help_text='Legal limit of foster children this home is licensed to host at once.'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=3, help_text='Years this family has been an active foster placement.'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='family_name',
            field=models.CharField(help_text='Family identifier (e.g. Johnson Family)', max_length=150),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='home_type',
            field=models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default='suburban', max_length=20),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='state',
            field=models.CharField(db_index=True, default='Texas', max_length=100),
        ),
    ]
