# Generated by Django 6.0.7 on 2026-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_fosterfamily_background_clearance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterfamily',
            name='current_occupants',
            field=models.TextField(blank=True, default='', help_text='Names and ages of all permanent household residents for background clearance.'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='email_address',
            field=models.EmailField(blank=True, default='', help_text='Contact email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='identity_doc_number',
            field=models.CharField(blank=True, default='', help_text='Aadhaar Card or official ID document number (Mandatory at least 1 person)', max_length=100),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='languages_spoken',
            field=models.CharField(blank=True, default='', help_text='Languages spoken in the home', max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='licensing_agency',
            field=models.CharField(blank=True, default='', help_text='Licensing agency name', max_length=150),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='licensing_worker_name',
            field=models.CharField(blank=True, default='', help_text='Assigned agency case manager overseeing this foster home', max_length=150),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='marital_status',
            field=models.CharField(blank=True, default='', help_text='Marital status & household composition details', max_length=100),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Primary phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='preferred_demographics',
            field=models.TextField(blank=True, default='', help_text='Preferred age range, gender, and sibling group preferences'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='references_info',
            field=models.TextField(blank=True, default='', help_text='Personal and professional references submitted during home study'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='residential_address',
            field=models.TextField(blank=True, default='', help_text='Full residential street address'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='special_trainings',
            field=models.TextField(blank=True, default='', help_text='Special training, certifications, or medical competencies'),
        ),
    ]
