# Generated by Django 6.0.7 on 2026-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_alter_fosterfamily_current_occupants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterfamily',
            name='primary_applicant_name',
            field=models.CharField(blank=True, default='', help_text='Full legal name(s) of the primary foster parent(s)', max_length=200),
        ),
    ]
