# Generated by Django 6.0.7 on 2026-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_alter_fosterfamily_primary_applicant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosterfamily',
            name='identity_document',
            field=models.ImageField(blank=True, help_text='Official Identity Document photograph / scan', null=True, upload_to='identity_documents/'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='identity_doc_number',
            field=models.CharField(blank=True, default='', help_text='Official ID document number (Driver License / Passport / Govt ID)', max_length=100),
        ),
    ]
