# Generated by Django 6.0.7 on 2026-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_fosterfamily_identity_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterfamily',
            name='current_occupants',
            field=models.TextField(blank=True, default='', help_text='Full names of all permanent household residents for background clearance.'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='languages_spoken',
            field=models.CharField(default='English', help_text='Primary language(s) spoken in the foster home (Mandatory field)', max_length=200),
        ),
    ]
