# Generated by Django 6.0.7 on 2026-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_alter_fosterfamily_current_occupants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterfamily',
            name='languages_spoken',
            field=models.CharField(default='', help_text='Primary language(s) spoken in the foster home (Mandatory field)', max_length=200),
        ),
    ]
