# Generated by Django 6.0.7 on 2026-08-02 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_alter_fosterfamily_languages_spoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fosterfamily',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who registered/added this foster family record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
