# Generated by Django 6.0.7 on 2026-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0008_fosterfamily_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosterfamily',
            name='preferred_demographics',
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='accept_sibling_placements',
            field=models.CharField(choices=[('None', 'None'), ('Yes', 'Yes'), ('No', 'No')], default='None', help_text='Willingness to accept sibling placements', max_length=10),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='behavioral_support_capacity',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', help_text='Behavioral support capacity', max_length=20),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='family_support_network',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', help_text='Family support network rating', max_length=20),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='household_composition',
            field=models.CharField(choices=[('None', 'None'), ('No children', 'No children'), ('One child', 'One child'), ('Two children', 'Two children'), ('Three or more children', 'Three or more children')], default='None', help_text='Household composition', max_length=50),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='housing_stability',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', help_text='Housing stability rating', max_length=20),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='long_term_placement_willingness',
            field=models.CharField(choices=[('None', 'None'), ('Yes', 'Yes'), ('No', 'No')], default='None', help_text='Long-term placement willingness', max_length=10),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='max_sibling_group_accepted',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum sibling group size accepted'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='medical_support_capacity',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', help_text='Medical support capacity', max_length=20),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='mental_health_support_capacity',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', help_text='Mental health support capacity', max_length=20),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='parenting_experience_years',
            field=models.PositiveSmallIntegerField(default=0, help_text='Parenting experience in years'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='preferred_age_group',
            field=models.CharField(choices=[('None', 'None'), ('0–5', '0–5'), ('6–10', '6–10'), ('11–15', '11–15'), ('16–18', '16–18'), ('Any age', 'Any age')], default='None', help_text='Preferred child age group', max_length=50),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='preferred_gender',
            field=models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='None', help_text='Preferred child gender', max_length=50),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='previous_foster_placements_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of previous foster placements hosted'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='successful_foster_placements_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of successful foster placements'),
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='therapy_support_availability',
            field=models.CharField(choices=[('None', 'None'), ('Yes', 'Yes'), ('No', 'No')], default='None', help_text='Therapy / counseling support availability', max_length=10),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='languages_spoken',
            field=models.CharField(choices=[('None', 'None'), ('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Gujarati'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Punjabi', 'Punjabi'), ('Urdu', 'Urdu'), ('Other', 'Other')], default='None', help_text='Primary language spoken in the home', max_length=100),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='marital_status',
            field=models.CharField(choices=[('None', 'None'), ('Single Parent', 'Single Parent'), ('Married Couple', 'Married Couple'), ('Joint Family', 'Joint Family'), ('Other', 'Other')], default='None', help_text='Marital status', max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='special_trainings',
            field=models.TextField(blank=True, default='', help_text='Special training & certifications (stored as comma-separated values)'),
        ),
    ]
