# Generated by Django 6.0.7 on 2026-08-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0010_fosterfamily_preferred_special_needs_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosterfamily',
            name='preferred_special_needs_category',
        ),
        migrations.AddField(
            model_name='fosterfamily',
            name='preferred_special_needs',
            field=models.CharField(choices=[('None', 'None'), ('Physical Disability', 'Physical Disability'), ('Developmental Disability', 'Developmental Disability'), ('Learning Disability', 'Learning Disability'), ('Medical Condition', 'Medical Condition'), ('Multiple Needs', 'Multiple Needs')], default='None', help_text='Preferred special needs category', max_length=50),
        ),
    ]
