# Generated by Django 6.0.7 on 2026-07-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('disrupted', 'Disrupted'), ('completed', 'Completed')], db_index=True, default='proposed', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('disruption_reason', models.TextField(blank=True, help_text='Filled in only when status = Disrupted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(help_text='If the child record is deleted, its placement history goes with it.', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='children.child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='families.fosterfamily')),
                ('placed_by', models.ForeignKey(blank=True, help_text='The case worker who recorded this placement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='placements__status_050fcb_idx')],
            },
        ),
    ]
