# Generated by Django 6.0.7 on 2026-07-30 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='is_override',
            field=models.BooleanField(default=False, help_text='Flagged when placement proceeds despite low ML score or safety warnings.'),
        ),
        migrations.AddField(
            model_name='placement',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placement',
            name='override_justification',
            field=models.TextField(blank=True, default='', help_text='Mandatory casework justification text provided when overriding ML recommendations.'),
        ),
        migrations.AddField(
            model_name='placement',
            name='override_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlacementOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('compatibility_score', models.FloatField(blank=True, null=True)),
                ('reasons', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='placements.placement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
