# Generated by Django 6.0.7 on 2026-08-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_placement_is_override_placement_override_by_and_more'),
        ('predictions', '0002_prediction_explanation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='Actual end date (filled on closure).', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='assigned_caseworker',
            field=models.CharField(blank=True, default='', help_text='Name of the caseworker assigned to oversee this placement.', max_length=200),
        ),
        migrations.AddField(
            model_name='placement',
            name='compatibility_score',
            field=models.FloatField(blank=True, help_text='Compatibility score (0.0-1.0) pulled from the linked prediction.', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='final_notes',
            field=models.TextField(blank=True, default='', help_text='Final case notes recorded at placement closure.'),
        ),
        migrations.AddField(
            model_name='placement',
            name='outcome',
            field=models.CharField(blank=True, choices=[('completed_successfully', 'Completed Successfully'), ('disrupted', 'Disrupted'), ('child_reunified', 'Child Reunified'), ('adopted', 'Adopted'), ('transfer', 'Transfer to Another Family')], default='', help_text='Final outcome (completed/disrupted placements only).', max_length=50),
        ),
        migrations.AddField(
            model_name='placement',
            name='placement_notes',
            field=models.TextField(blank=True, default='', help_text='General placement notes and context.'),
        ),
        migrations.AddField(
            model_name='placement',
            name='placement_type',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('short_term', 'Short-Term'), ('long_term', 'Long-Term'), ('respite', 'Respite')], default='', help_text='Classification of the placement type.', max_length=20),
        ),
        migrations.AddField(
            model_name='placement',
            name='prediction',
            field=models.ForeignKey(blank=True, help_text='The ML prediction that informed this placement decision (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='predictions.prediction'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected end date.', null=True),
        ),
    ]
