# Generated by Django 6.0.7 on 2026-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(choices=[('technical', 'Technical Support'), ('training', 'Training & Onboarding'), ('data', 'Data & Privacy'), ('access', 'Account Access'), ('feedback', 'Feedback & Suggestions'), ('other', 'Other')], default='other', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Mark whether admin has reviewed this message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
