# Generated by Django 6.0.7 on 2026-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Synthetic identifier only — never a real child's name.", max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('special_needs', models.BooleanField(default=False)),
                ('sibling_group_size', models.PositiveSmallIntegerField(default=1, help_text='1 means the child has no siblings needing joint placement.')),
                ('behavioral_notes_score', models.FloatField(help_text='Synthetic 0.0-1.0 severity index used as an ML feature.')),
                ('education_level', models.CharField(max_length=50)),
                ('time_in_care_months', models.PositiveIntegerField(help_text='How long the child has been in the care system so far.')),
                ('is_placed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'is_placed'], name='children_ch_state_4ce907_idx')],
            },
        ),
    ]
