# Generated by Django 6.0.7 on 2026-07-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='sibling_group_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier grouping siblings together for joint placement.', max_length=50),
        ),
    ]
