# Generated by Django 6.0.7 on 2026-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_sibling_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='blood_group',
            field=models.CharField(choices=[('Unknown', 'Unknown / Not Tested'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Unknown', help_text='Emergency medical blood group', max_length=10),
        ),
        migrations.AddField(
            model_name='child',
            name='case_notes',
            field=models.TextField(blank=True, default='', help_text='Trauma history, sibling placement notes, or behavioral triggers'),
        ),
        migrations.AddField(
            model_name='child',
            name='caseworker_contact',
            field=models.CharField(blank=True, default='', help_text='Caseworker phone or email contact details', max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='caseworker_name',
            field=models.CharField(default='Unassigned', help_text='Primary Social Worker / Caseworker assigned', max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='dietary_preferences',
            field=models.CharField(blank=True, default='', help_text='Dietary preferences & restrictions', max_length=255),
        ),
        migrations.AddField(
            model_name='child',
            name='ethnicity',
            field=models.CharField(blank=True, default='', help_text='Ethnicity / Cultural background', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Last name', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='legal_status',
            field=models.CharField(choices=[('Temporary Custody', 'Temporary Custody'), ('Permanent Ward', 'Permanent Ward'), ('Voluntary Placement', 'Voluntary Placement'), ('Court-Ordered', 'Court-Ordered'), ('Under Investigation', 'Under Investigation')], default='Temporary Custody', help_text='Legal custody type', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='medical_history',
            field=models.TextField(blank=True, default='', help_text='Detailed medical history & conditions'),
        ),
        migrations.AddField(
            model_name='child',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='Middle name', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='nationality',
            field=models.CharField(blank=True, default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, help_text='Child photograph', null=True, upload_to='children_photos/'),
        ),
        migrations.AddField(
            model_name='child',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='school_info',
            field=models.CharField(blank=True, default='', help_text='School & grade information', max_length=255),
        ),
        migrations.AddField(
            model_name='child',
            name='severe_allergies',
            field=models.CharField(blank=True, default='None', help_text='Known severe allergies (e.g., peanuts, penicillin)', max_length=255),
        ),
        migrations.AddField(
            model_name='child',
            name='special_needs_details',
            field=models.TextField(blank=True, default='', help_text='Special needs & accommodation details'),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Age in years (0-17)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='behavioral_notes_score',
            field=models.FloatField(default=0.5, help_text='Synthetic 0.0-1.0 severity index used as an ML feature.'),
        ),
        migrations.AlterField(
            model_name='child',
            name='education_level',
            field=models.CharField(default='Elementary', max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='sibling_group_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identifier grouping siblings together for joint placement.', max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='state',
            field=models.CharField(db_index=True, default='Texas', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='time_in_care_months',
            field=models.PositiveIntegerField(default=6, help_text='How long the child has been in the care system so far.'),
        ),
    ]
