# Generated by Django 6.0.7 on 2026-07-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_blood_group_child_case_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='caseworker_name',
            field=models.CharField(choices=[('Caseworker', 'Caseworker'), ('Social Worker', 'Social Worker'), ('Care Coordinator', 'Care Coordinator'), ('Unassigned', 'Unassigned')], default='Caseworker', help_text='Primary Social Worker / Caseworker assigned', max_length=150),
        ),
    ]
