# Generated by Django 6.0.7 on 2026-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_child_caseworker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='languages_spoken',
            field=models.CharField(blank=True, default='English', help_text='Primary language(s) spoken by the child (e.g. English, Spanish)', max_length=200),
        ),
    ]
