# Generated by Django 6.0.7 on 2026-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_child_languages_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='languages_spoken',
            field=models.CharField(blank=True, default='', help_text='Primary language(s) spoken by the child (e.g. English, Spanish)', max_length=200),
        ),
    ]
