# Generated by Django 6.0.7 on 2026-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_alter_child_languages_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
