# Generated by Django 6.0.7 on 2026-08-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_alter_child_caseworker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='languages_spoken',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Gujarati'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Punjabi', 'Punjabi'), ('Urdu', 'Urdu'), ('Other', 'Other')], default='English', help_text='Primary language spoken by the child', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='special_needs',
            field=models.CharField(choices=[('None', 'None'), ('Physical disability', 'Physical disability'), ('Developmental disability', 'Developmental disability'), ('Learning disability', 'Learning disability'), ('Medical condition', 'Medical condition'), ('Multiple special needs', 'Multiple special needs')], default='None', help_text='Special needs category requirement', max_length=100),
        ),
    ]
