# Generated by Django 6.0.7 on 2026-08-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0009_alter_child_languages_spoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='behavioral_support_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Behavioral support level required', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='medical_needs_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Medical needs level required', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='mental_health_support_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Mental health support level required', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='needs_sibling_placement',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Requires joint sibling placement', max_length=10),
        ),
        migrations.AddField(
            model_name='child',
            name='previous_foster_placements',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of previous foster care placements'),
        ),
        migrations.AddField(
            model_name='child',
            name='trauma_severity_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Trauma severity level', max_length=20),
        ),
    ]
