# Generated by Django 6.0.7 on 2026-08-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0011_alter_child_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='school_attendance_status',
            field=models.CharField(choices=[('None', 'None'), ('Regular', 'Regular'), ('Irregular', 'Irregular'), ('Not Enrolled', 'Not Enrolled')], default='None', help_text='School attendance status', max_length=50),
        ),
    ]
