# Generated by Django 6.0.7 on 2026-07-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(help_text='Public government report URL this was scraped from.')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML')], max_length=10)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='reports/raw/')),
                ('parsed_text', models.TextField(blank=True, help_text='Cleaned plain-text extraction, used for keyword search.')),
                ('published_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('metric_name', models.CharField(help_text="e.g. 'children_in_foster_care', 'successful_placements'.", max_length=150)),
                ('value', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='reports.report')),
            ],
            options={
                'ordering': ['state', 'year'],
                'indexes': [models.Index(fields=['state', 'year', 'metric_name'], name='reports_rep_state_a00a2a_idx')],
            },
        ),
    ]
